# Generated by Django 3.0.4 on 2020-04-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritepublisher',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='favouritepublisher',
            name='source_url',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
