# Generated by Django 3.0.4 on 2020-04-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_auto_20200402_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritepublisher',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='favouritepublisher',
            name='source_url',
            field=models.CharField(max_length=1000),
        ),
    ]
