# Generated by Django 3.0.4 on 2020-04-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0004_favouritepublisher_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritepublisher',
            name='slug',
            field=models.CharField(max_length=100),
        ),
    ]
